apiVersion: v1
kind: Namespace
metadata:
  name: static
---
apiVersion: v1
kind: Deployment
metadata:
  name: k8s-static
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 865563157914.dkr.ecr.ap-south-1.amazonaws.com/staticwebsite:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-static-svc
  namespace: static
spec:
  selector: 
    app: static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

