apiVersion: v1
kind: deployment
metadata:
  name: static
  namespace: static
spec:
  selector:
    matchLabels:
      app: static
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: 865563157914.dkr.ecr.us-east-2.amazonaws.com/static:latest
        ports:
        - containerPort: 80
